### ISSUE TITLE
libxslt-dev on Amazon Linux/Redhat 6.x

### ISSUE THREAD

**Issue by danhiris** [evertrue/s3_dir#7]
I get the exception when I try to use the cookbook.
 
yum_package[libxslt-dev] (et_fog::default line 30) had an error: Chef::Exceptions::Package: No candidate version available for libxslt-dev

The package name on these systems is different:

yum search libxslt-dev
Loaded plugins: priorities, update-motd, upgrade-helper
====================================== N/S matched: libxslt-dev ======================================
libxslt-devel.x86_64 : Development files for libxslt

**Comment by jeffbyrnes** [comment]
@danhiris sorry to hear that, but this cookbook doesn’t install any packages. You’ll want to look upstream (`et_fog`? `s3_file`? A cookbook one of those two depends on?) to find where this is coming from.

**Comment by danhiris** [comment]
I found that it's looking for an old version of et_fog, which doesn't have logic to check for Redhat distros.

**Comment by jeffbyrnes** [comment]
Ah! Well then, that’s being tracked as #8, and I have a fix ready to go. Just need @eherot to re-add my write permissions here, and I’ll get us all sorted.

In the meantime, you can add this to your `Berksfile` to keep moving forward:

```ruby
cookbook 's3_dir', github: 'jeffbyrnes/s3_dir'
```

That’ll grab my fork w/ the fixes all stacked up & ready to rock.

**Comment by jeffbyrnes** [comment]
Closed via 30ff899
