### ISSUE TITLE
Version dependencies out of date

### ISSUE THREAD

**Issue by chrisferry** [evertrue/s3_dir#8]
Please bump dependencies on et_fog to 4.0.X
Or at least move away from ~> and use >=
Currently can't use this project as it's tied to an old version of et_fog
that is then tied to build-essentials 2.X.
Basically stuck in a dependency hell :)

**Comment by jeffbyrnes** [comment]
@chrisferry thanks for letting us know. I’ve got a fix stacked up, though I’ll need @eherot to grant me write permissions to this repo again so I can ship it :)

**Comment by jeffbyrnes** [comment]
@chrisferry please check out my comment on #7 on how to use my fixes while I’m waiting to get them merged in here & a proper release cut.

**Comment by eherot** [comment]
@jeffbyrnes granted you write access
